-- Tabella per monitorare offerte specifiche Ikea
CREATE TABLE IF NOT EXISTS `monitor_offer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ikeaId` BIGINT NOT NULL,
  `name` VARCHAR(500) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_ikeaId` (`ikeaId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

